config:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  printer_width: 80
  write_json: true
  warn_error: true
  log_format: default
  debug: false
  version_check: true
  fail_fast: true
  indirect_selection: cautious
  use_experimental_parser: false
  static_parser: true
  cache_selected_only: false
  populate_cache: true

