name: dbt Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TAG_STEM: dbt
  TEST_TAG: test
  LATEST_TAG: latest
  DOCKERFILE_FOLDER: .
  MAJOR_VERSION: 1
  DSLIM_HTTP_PROBE: false
  DOCKERHUB_REPO_OWNER: aaweaver9
  DOCKERHUB_REPO: aaweaver9/dbt

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_REPO_OWNER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    needs: login
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build the image for all platforms
    - uses: mr-smithers-excellent/docker-build-push@v6.3
      name: Build the ${{ env.DOCKERHUB_REPO }} image
      with:
        image: ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }}
        registry: docker.io
        dockerfile: ${{ env.DOCKERFILE_FOLDER }}/${{ env.TAG_STEM }}.Dockerfile
        username: ${{ env.DOCKERHUB_REPO_OWNER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: ${{ env.LATEST_TAG }}, v${{ env.MAJOR_VERSION }}.${{ github.run_number }}
      
    # Push only the slim image to Docker Hub
    - name: Push images to Docker Hub
      run: |
        docker image push ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }} --all-tags
